application: version-is
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Static files
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
# Tasks / Cron jobs
- url: /tasks/get-versions
  script: task_get.app
  login: admin
- url: /tasks/get-tags
  script: task_get_by_tags.app
  login: admin
# Catch rest to API
- url: /.*
  script: api.app